name: Package Analysis

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v1
      - name: Dart/Flutter Package Analyzer
        uses: axel-op/dart_package_analyzer@v1.1.0
